- cmd/client-daemon.go
- cmd/client.go
- go.mod
- go.sum
Old daemon was mostly pseudocode, new stuff works with an orchestration system. Still needs a lot of work, but functionally a daemon now :)
> fix: daemon overhaul

- cmd/client.go
- scripts/.gitignore
- scripts/install.sh
Need this for getting deps quickly set up on EC2 or spot instances.
> fix: simple install script

- cmd/client-dump.go
- cmd/client-restore.go
- utils/compress.go
- utils/config.go
- zipping was busted, rewrote 
- logformatting 
- should check for latest zip files when looking at a checkpoint to decompress
> fix: lots of little things

- cmd/client-dump.go
- Added a quick hack to check for pyTorch checkpoints before dumping.
> fix: hacks

- cmd/client-daemon.go
- cmd/client-dump.go
- cmd/client.go
- switched to jetstream for more durability 
- more reliable daemon 
- less finnicky orchestrator/client relationship
> fix: nats -> jetstream

- .goreleaser.yaml
- testing jira & github integration
> fix: goreleaser update

- cmd/client-daemon.go
- cmd/client-dump.go
- cmd/client.go
- go.mod
- go.sum
- rewrote jetstream to be less hacky using the new API 
- Added support for heartbeat checkpoints
> OAK-17: new jetstream API

- cmd/client-dump.go
- cmd/client.go
- cmd/version.go
- main.go
- quick logging fixes 
- version command (OAK-36)
> fix: version cmd added

- .vscode/launch.json
- cmd/client-daemon.go
- cmd/client-dump.go
- cmd/client.go
TIL timers and tickers aren't the same thing :facepalm:
> fix: misc-cleanups

- cmd/client-dump.go
- cmd/client-restore.go
- Separates out code for pytorch checkpoint/restore 
- Logging cleanup
> fix: checkpoint/restore separation

- cmd/client-daemon.go
- cmd/client-dump.go
- cmd/client-restore.go
- cmd/client.go
- checkpointState -> cedanaState. Consolidated the ClientState w/ CedanaState for better readability. We might be shipping too much information now, but we can optimize that later.
> fix: refactor state a little

- cmd/client-dump.go
- cmd/client-restore.go
- utils/compress.go
Unzip complexity is harebrained, no more internal openFds directory
> fix: revert complexity

- cmd/client.go
- cmd/client_test.go
- go.mod
- go.sum
- Added a quick test for the client, some filesystem abstraction
> fix: test looks good

- cmd/client.go
There's sometimes a race condition when restoring a process if the NATS daemon isn't up on the client, so the restore command gets dropped.
> CED-12: switch NATS policy

- cmd/client-dump.go
- cmd/client-restore.go
- cmd/client.go
- go.mod
- go.sum
- utils/config.go
- utils/store.go
We want interop between storing checkpoints in minio & in NATS (for self-serve). With all the testing work being done as well, it's useful to be able to mock it out too. 
https://github.com/cedana/cedana/issues/64
> CED-78: Checkpoint storage abstractions

- test/benchmarks/benchmark_analysis.py
- test/benchmarks/large_data_benchmark.sh
Give this a try and if it doesn't work, add some comments and I'll take a look tonight
> fix: file routing fiex

- api/server.go
Quick fix to get tasks running based off config json that is created from instantiation of client
> fix: properly grab task to run from config

- cmd/client-daemon.go
> fix: switched logger location

- api/dump.go
- api/restore.go
- cmd/debug.go
- go.mod
- go.sum
- test/benchmarks/benchmark.py
- utils/compress.go
- utils/profiling.go
- utils/store.go
- Switch to tar 
- Try out fgprof instead of pprof
> fix: switch to tar, try new profiler

- api/client.go
- api/dump.go
- api/restore.go
- api/server.go
- scripts/ci/benchmark-and-push.sh
- test/benchmarks/benchmark.py
- utils/profiling.go
- utils/store.go
Nothing fancy, just a way for us to get more granular detail on operations that we want timings on.
> Basic timing instrumentation for profiling

- test/benchmarks/Dockerfile
- test/benchmarks/benchmark.py
> fix: add cde, install code

- test/benchmarks/benchmark.py
- test/benchmarks/entrypoint.sh
Requires https://github.com/cedana/cedana-benchmarking/tree/feat/ced-319
> run terminal checkpoint from job using gRPC

- test/benchmarks/performance.py
Problematic behavior:
Corrected behavior:
> Fix bug introduced by PR #168 causing benchmark tests to be run after correctness tests

- .github/workflows/test.yml
> hotfix: Revert test CI dependency on build

- scripts/k8s/setup-host.sh
- pass systemctl into build start daemon
n/a
> fix: start cedana on eks with systemctl

- scripts/k8s/setup-host.sh
Host setup script wasn't checking for amzn2, is now.
> fix: setup host script

- api/server.go
> Add grpc interceptors 

- api/runc.go
- api/runc/runc.go
- api/server.go
- Reverted localhost:8080 for the daemon to 0.0.0.0:8080
[CED-420](https://linear.app/cedana/issue/CED-420/fix-grpc-server-back-to-8080-instead-of-localhost8080)
> fix: revert localhost to 0.0.0.0

- scripts/ci/regression-test.sh
- scripts/ci/smoke-test.sh
- test/benchmarks/cedana_bindings.py
Wrapped our bash functions and added a try/catch for failing `git describe` in our code.
> Hotfix: Smoke test silent failures

- scripts/k8s/setup-host.sh
Add some missing packages + install packages one by one to properly report error rather than failing in batch.
CED-375
> EKS setup for Amazon Linux 2023

- api/runc/runc.go
- cmd/helper.go
> Fix: Add log scraping for daemon from helper & fix host prefix for runcId discovery

- api/process.go
> Fix logging for stderr and stdout pipes being closed 

- .github/workflows/release.yml
> Hotfix: run install scripts on release too 

- cmd/daemon.go
> fix: add CUDA 12.2 to version matrix

- .github/workflows/build.yml
- .github/workflows/release.yml
> hotfix: Update release yml

- cmd/dump.go
Fix GPU flag not recognized by `cedana dump process`
CED-464
> Fix GPU flag not recognized by `cedana dump process`

- cmd/scripts/k8s/cleanup-host.sh
- Remove cedana binary that gets copied from cedana-helper image on attach
n/a
> fix: cedana binary needs removed from host on cleanup

- README.md
Small refresh of the README file, fixing typos and updating some information.
NA
> docs: fix README typos and small updates

- cmd/scripts/k8s/setup-host.sh
- Avoid writing over bashrc for k8s env
n/a
> fix: avoid writing over bashrc

- .github/workflows/release.yml
Release is blocked
Note: untested, technically, can't be tested until we actually make a release.
> fix: permissions for upload manifests job

- build-start-daemon.sh
Minor fix for logs and removes redundant `cp`.
No
No
> fix: logs and remove redundant `cp`

- Dockerfile
- cmd/root.go
- cmd/version.go
- main.go
I am using this to make it easier to test which version is loaded into the image.
```
docker run -it --rm cedana/cedana-helper:<ref> cedana -v
```
None
> feat: load version definition at compile time

- utils/config.go
Currently, with root user, if env variable is not set we fail.
This means most non-sudo envs fail to get user.
> fix: support auto fetch root user

- api/crio/crio.go
- cmd/scripts/k8s/cleanup-host.sh
- Lchown files that are of mode symlink
[CED-538](https://linear.app/cedana/issue/CED-538/fix-symlink-ownership-not-changing-in-crio-sysbox-rootfs)
> fix: symlink ownership changes

- api/crio/crio.go
- fix not authenticating _before_ pulling image
n/a
> fix: auth before pull

- cmd/scripts/k8s/setup-host.sh
- remove installation of go on nodes
[CED-539](https://linear.app/cedana/issue/CED-539/go-is-getting-installed-on-nodes)
> fix: no more go installing on nodes

- cmd/scripts/k8s/setup-host.sh
- Remove packages not being used
- Add default config dpkg opts to packages installed for buildah, cedana, and crio - thanks Everton!
n/a
> hotfix: Add dpkg conf and remove unused packages

- cmd/dump.go
- cmd/restore.go
More info (like stats) could be useful when doing C/R from the CLI. Currently the response returned is anyways too brief.
CED-563
> NOPE.
> Include more info in CLI response

- reset.sh
Remove dependence on SUDO. Makes running tests in minimal reproduction scenarios like containers or with nix easier.
> fix: remove sudo from reset.sh

- cmd/restore.go
> Add PID to successful restore response

- api/runc.go
- Detect whether a job has tcp connections
- Add tcp established and tcp close based on the above
[CED-573](https://linear.app/cedana/issue/CED-573/detect-tcp-connections-by-scanning-procpidnettcp)
> feat: analyze tcp connections

- cmd/scripts/k8s/setup-host.sh
Release is broken on arm platforms.
> fix: platform detection code

- README.md
- docs/README.md
- docs/kata.md
- docs/support/runtimes.md
Docs have been lacking, added a docs folder and moving all repo-related documentation and diagrams into here.
> Feat: refresh documentation 

- .github/workflows/pr.yml
- hotfix path to utils test
n/a
**This is to fix unit tests**
**No README changes necessary**
**No**
> fix: path to utils test

- cmd/scripts/k8s/setup-host.sh
go is not needed any more, it's a useless install.
> fix: remove go download from setup

- pkg/api/server.go
When the request failed, the error returned was still nil, so the daemon was proceeding.
NA
> Hotfix: GPU binary download error handling

- .github/workflows/pr.yml
- .github/workflows/release.yml
> Hotfix: Skip PR/benchmark step when reusing workflow

- .github/workflows/manual.yml
- .github/workflows/pr.yml
- .github/workflows/push.yml
- .github/workflows/release.yml
> Hotfix: Skip PR/benchmark step when reusing workflow #330

- cmd/root.go
- pkg/api/containerd.go
- pkg/api/crio.go
- pkg/api/dump.go
- pkg/api/notify.go
- pkg/api/restore.go
- pkg/api/server.go
- pkg/container/checkpoint.go
- pkg/container/notify_socket.go
- pkg/container/restore.go
- pkg/container/rootless_linux.go
- pkg/container/runc_utils.go
- pkg/container/signals.go
- pkg/container/utils_linux.go
- pkg/utils/logger.go
Remove all the last bits of remaining logging that are not global. This is the last step in making
logging fully global.
CED-677
> Make logging fully global

- pkg/api/dump.go
- pkg/api/runc.go
> Hotfix: Fix leave_running config var typo

- go.mod
- go.sum
- pkg/api/asr.go
Adds crio support. It's doesn't support diskio currently as I am also trying to figure out if or how we can convert it into a percent like metric.
Fix CED-660
> feat: asr support for crio

- pkg/api/server.go
- pkg/utils/config.go
- pkg/utils/id.go
- pkg/utils/otel.go
machine-id for some reason isn't cutting it as a unique enough identifier. Adding mac addr and hostname to otel traces.
CED-696
> hotfix: hostname + mac addr

- .github/workflows/manual.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
> Update to dockerhub images for CI

- cmd/scripts/k8s/setup-host.sh
nftables dep is broken for apt, this breaks new installs.
> fix: add nftables dep

- cmd/daemon.go
We are getting failure logs for this in benchmarks and tests. This will ensure we don't anymore.
> fix: remove daemon asr reporting when metrics disabled

- cmd/helper.go
Dial API may get removed in a future Go version. Consider switching to using healthcheck instead.
> fix: use healthcheck instead of dial

- .github/workflows/pr.yml
- Dockerfile
- cmd/scripts/k8s/setup-host.sh
- setup-host.sh
We currently don't test setup host scripts.
- Add CI for testing setup host script.
- Split the CI script out of string, provides linting and auto-complete.
> feat: add setup host scripts test ci

- pkg/api/dump.go
- pkg/api/server.go
> Nil dereference w/ starting daemon & dump

- .github/workflows/pr.yml
- .github/workflows/push.yml
- .github/workflows/release.yml
> Hotfix: skip helper test image push on release

- cmd/daemon.go
- pkg/api/server.go
Added check for CEDANA_URL, made sure endpoint for gcloud service account was valid, added some more attributes to pubsub data.
> CED-745: moved some stuff around, added mem for pricing

- cmd/daemon.go
> hotfix: add missing attribute to asr data 

- cmd/flags.go
- cmd/recvtty.go
- setup-host.sh
- test/regression/main.bats
broken images helper images setup-host script fix.
> hotfix: criu download url fix

- cmd/root.go
- go.mod
Disables all cadvisor and klog outputs.
> fix: disable klog

- pkg/api/runc.go
This is a runc query bug. Tested the PR, the said bug affects all endpoints except specifically `/restore` lmao.
The point is, if it's container not found error then we still append the container to the list of containers we return with runcQuery containers. Doing a continue for that case should fix the issue.
Though we also need to return an error if it's an empty list as that is what use to continue the loop on controller rest api side.
This regression was introduced in:  https://github.com/cedana/cedana/pull/363
This is in-fact quite easy to reproduce.
The method to reproduce it is,
- Use it on a multi node cluster (on a single node cluster you can try making a request with wrong container name, and it will give error message without runcDiscoveryErr). But technically, we can't hit …
> fix: runc query bug

- cmd/restore.go
> checkpoint -> restore

- .github/workflows/pr.yml
Shellcheck makes too much noise, and most of it is info-level suggestions.
> Shellcheck to report warnings/errors only

- pkg/api/restore.go
This was accidentally changed in https://github.com/cedana/cedana/pull/405/files#diff-fe7181eb5379f90e2e9e9f84a491e15c26210b777b4f46aae9f485355bbfe45cL634
Reverting it back to the original value.
> hotfix: GPU restore streaming

- pkg/api/restore.go
> hotfix: tmp dir was not being deleted after restore

- pkg/api/gpu.go
- pkg/api/process.go
- pkg/api/restore.go
> hotfix: Fix GPU process restore shm issue (re-occuring)

- pkg/api/process.go
- pkg/api/runc.go
- pkg/utils/processes.go
Fixes a nil deref, when DB return nothing for a query.
> fix: nil deref in runc query

- pkg/api/gpu.go
- pkg/api/restore.go
> Removal of UnblockBarrier

- cmd/helper.go
- cmd/scripts/k8s/setup-host.sh
- pkg/api/gpu.go
- setup-host.sh
Replaces PR #421 
fixes CED-782
> feat: handle automatic shim dl

- docs/cedana-image-streamer/cedana-image-streamer.md
Include a note that GPU streaming does not support all jobs, notably LLM inference.
> Mention support limitations for GPU streaming

- .github/workflows/manual.yml
- .github/workflows/pr.yml
- .github/workflows/push.yml
- .github/workflows/release.yml
- scripts/ci/helpers.sh
Secrets and vars were cleaned up, and many common ones moved to org level. This PR updates the CI to
use the new secrets and vars. Formatting standardized for GH workflow files.
> ci: update secrets and vars

- build-start-daemon.sh
- cmd/scripts/k8s/bump-restart.sh
- cmd/scripts/k8s/setup-host.sh
> hotfix: aws setup script for Kubernetes

- internal/server/server.go
- pkg/config/config.go
- pkg/config/types.go
- pkg/plugins/core.go
Following addition to the config:
https://github.com/cedana/cedana/blob/43e5b267291a933ef93c89628153b6d315df4efa/pkg/config/types.go#L81-L88
Can also set env vars `CEDANA_PLUGINS_LIB_DIR` and `CEDANA_PLUGINS_BIN_DIR` to override just as for
other config values.
This is needed for testing/benchmarking infra.
> feat: Allow custom plugin lib/bin directory

- Makefile
Automatically run dependent steps in Makefile, effectively making `make start` the entrypoint to a barebones cedana.
Not unnecessarily repeating previously run steps:
Also included sudo use where appropriate to resolve
```
/home/ubuntu/cedana/scripts/systemd-reset.sh: line 26: /var/log/cedana-daemon.log: Permission denied
```
> Automatically run dependent steps while ensuring no repetition

- docs/README.md
Update paths and commands to be up to date with plugins changes.
> Update quick start README

- Makefile
- plugins/kata/README.md
Improve globbing to ensure source code changes are captured.
> Hotfix: not rebuilding on binary source changes

- cmd/dump.go
- internal/server/criu/dump_handlers.go
- internal/server/gpu/manager_simple.go
- internal/server/gpu/run_adapters.go
- pkg/criu/criu.go
- pkg/criu/notify.go
- pkg/criu/notify_callback.go
- pkg/criu/notify_callback_multi.go
- pkg/flags/cmd.go
- plugins/runc/pkg/gpu/interception.go
> Hotfixes: GPU lifecycle and weird behavior 

- go.mod
- go.sum
- internal/server/criu/checks.go
- internal/server/gpu/manager_simple.go
Enable `--leave-running` for GPU:
> Forward `--leave-running` option from daemon, remove outdated error message

- internal/db/db_sqlite.go
- internal/db/sql/job.sql
- internal/db/sql/job.sql.go
- internal/db/sql/models.go
- internal/db/sql/schema.sql
- internal/server/filesystem/dump_adapters.go
- internal/server/filesystem/restore_adapters.go
- internal/server/job/manager_lazy.go
- pkg/client/client.go
- pkg/utils/files.go
- pkg/utils/slice.go
GPU restore was failing because now we spawn the controller as the user, which requires the dump dir
to have appropriate perms.
> hotfix: User creds not saved in DB + dump dir perms issue

- pkg/config/config.go
> Hotfix: config not picking up connection struct

- plugins/k8s/cmd/helper.go
The daemon in k8x needs to be started with TCP at 0.0.0.0:[port].
> fix: k8s-helper to start daemon w/ TCP

- plugins/k8s/cmd/helper.go
> hotfix: params inverted

- cmd/restore.go
- internal/server/criu/restore_handlers.go
- internal/server/process/dump_adapters.go
- internal/server/process/restore_adapters.go
Added exception for anon_inode fds in checkpoint and restore.
> Add --link-remap for shm objects

- internal/server/job/job.go
- internal/server/job/manager_lazy.go
- test/regression/helpers/daemon.bash
> Hotfix: DB caching for remote

- pkg/criu/criu.go
- test/regression/helpers/daemon.bash
A common reason for flaky CI tests was the 'broken pipe' error when RPC-ing with CRIU.
> fix: Intermittent CRIU broken pipe errors

- internal/server/job/manager_lazy.go
> Hotfix: change order of db sync to fetch checkpoints 

- go.mod
For compatibility with the Beta9 integration.
> downgrade: golang version to 1.22.7

- go.mod
- go.sum
- internal/server/gpu/manager_simple.go
Supports GPU controller [PR #123](https://github.com/cedana/cedana-gpu/pull/123).
> `--leave-running` propagation for prune `cudaCallList`

- internal/server/server.go
Makes our daemon more controllable via APIs.
> Add server reflection to cedana grpc server

- scripts/host/k8s-install-plugins.sh
Report status of shim install.
> fix: handle shim install reporting

- .github/workflows/release.yml
- .goreleaser.yaml
- go.sum
Update release workflows to include CLH and Kata plugin binaries.
> Update release workflow for CLH & Kata

- .github/workflows/pr.yml
- Makefile
- test/Dockerfile.cuda
- test/regression/basic.bats
- test/regression/cr.bats
- test/regression/helpers/daemon.bash
- test/regression/helpers/gpu.bash
- test/regression/manage.bats
- test/regression/plugins/gpu.bats
- test/regression/plugins/runc.bats
- test/regression/plugins/streamer.bats
- test/regression/profiling.bats
- test/regression/run.bats
Adds scaffolding to run more complex workloads in our regression test suite like inference. More work TBD to add models + training + HPC-style workloads.
> Feat: Add inference tests to GPU suite

- go.mod
- go.sum
> chore: update proto apis

- .github/workflows/pr.yml
- go.mod
- go.sum
- internal/server/gpu/manager_simple.go
- pkg/criu/criu.go
- pkg/criu/notify.go
- pkg/criu/notify_callback.go
- pkg/criu/notify_callback_multi.go
Accompanying PRs:
- https://github.com/cedana/cedana-api/pull/68
- https://github.com/cedana/cedana-gpu/pull/140
> Add GPU unfreeze RPC call

- .github/workflows/test_gpu.yml
> Disable 11.8 & 12.2 CUDA tests for now

- .goreleaser.yaml
Github release has been failing due to this change. Reverting it.
> Fix goreleaser.yaml

- internal/metrics/otel.go
> Hotfix: SigNoz Traces Auth

- .github/workflows/test.yml
- .github/workflows/test_gpu.yml
- .github/workflows/test_streamer.yml
Turns out bats test retries are causing the test run to succeed regardless of any failures. Not sure
why this is the behavior as I was under the impression they were passing because only the first
attempt was failing, but it seems that the retries are causing the test to pass regardless.
Also, a global `RETRIES` for all tests is never a good idea. Most tests are not flaky, and are expected to pass in the first attempt.
> hotfix: Remove test retries

- internal/cedana/criu/dump_handlers.go
> hotfix: bump ghost file max size from 10 -> 200MB

- internal/metrics/otel.go
- pkg/logging/logger.go
- pkg/logging/signoz.go
> Signoz logging hotfix

- pkg/logging/signoz.go
> Hotfix: Add cedana url to logs 

- plugins/k8s/cmd/helper.go
will add new and test different configurations here,
> hotfix: reduce concurrency

- plugins/k8s/cmd/helper.go
> CED-1356: fix: reduce rmq concurrency

- plugins/runc/internal/cgroup/dump_adapters.go
- plugins/runc/internal/container/dump_adapters.go
- plugins/runc/internal/container/restore_adapters.go
> CED-1377: crcr cgroup

- internal/cedana/server.go
- internal/metrics/otel.go
Ensure correct version and connection url are reported by trace provider.
> CED-1411: fix: add trace resource attributes

- internal/cedana/gpu/controller.go
- internal/cedana/gpu/manager_pool.go
- internal/cedana/streamer/fs.go
- plugins/storage-s3/s3/storage.go
Checks early for bucket existence to fail early.
> CED-1610: Fix `storage/s3` error handling

- .github/workflows/test_k8s.yml
- internal/cedana/streamer/dump_adapters.go
- test/k8s/k3s.bats
Same as title. Disabled until pause image pull issue fixed.
> ced-1613: Temporarily disable k3s tests
