cedana/cedana

cmd/bootstrap.go, utils/config.go
Autoconfig stuff was hideously broken, resolved a large server override bug too (where it just doesn't load). 
Bootstrapping a cedana client is a lot cleaner now.
=> fix: quick bugfix

cmd/bootstrap.go, utils/config.go
stupid bug introduced by trying to fix the issue where running cedana w/ sudo grabs the root user. we shouldn't even be using the homedir as a var anyway, but that's a fix for later
=> fix: bug with getenv(USER)

cmd/client-daemon.go, cmd/client-dump.go, cmd/client-restore.go, cmd/client.go, utils/config.go, utils/files.go
- MVP for filesystem checkpointing, open files are sent as part of a larger checkpoint 
- Pytorch checkpointing more robust 
- Restore command rewritten for ease of use w/ commandline
=> fix: rewrite of restore and dump commands

cmd/client.go, go.mod, go.sum
Bumped NATS - NATS on the CLI and in `cedana` were different, to bring them both forwards had to update some functions that were renamed upstream.
=> CLI-27: `cedana` as source of truth for interfaces

api/client.go, api/client_test.go, api/daemon.go, api/dump.go, api/restore.go, api/tcp_test.go, cmd/bootstrap.go, cmd/cli.go, cmd/client-daemon.go, cmd/client.go, cmd/debug.go, dev.sh, go.mod, test/benchmarks/Dockerfile, test/benchmarks/dump_test.go, test/benchmarks/restore_test.go, utils/override.go
Bit of a refactor, moving code around so core capabilities can only be called via RPC. Daemon is now also more of a daemon, and listens on /tmp/cedana.sock. 
Still a lot of features to implement back, but purpose of this ticket is to gain back parity with what it was like pre-refactor.
=> CED-139: Reorganize into RPC 

cmd/cli.go, cmd/debug.go
Changes:
- Made dump and restore root commands:
- Commands look like: dump process, dump containerd, dump runc
- Same for restore
=> fix: better cli commands for dump and restore (containerd-runc-process)

cmd/cedana-helper/Dockerfile
The branch `feat/gce-99` has now been merged in the main branch and no longer exists in the upstream repository.
=> cedana-helper: update dockerfile

test/benchmarks/correctness.py, test/benchmarks/process_json.py
Example of diff checkpoint test at end of correctness execution:
Example of output when checkpoints are different:
Example of output when checkpoints are same:
=> Use process_json.diff_ckpts in correctness.py, add error msg

api/process.go
If an existing JID is given to `cedana exec ...`, the command fails, but the daemon is still running the job.
[CED-385 : Fix job running despite existing job ID error](https://linear.app/cedana/issue/CED-385/fix-job-running-despite-existing-job-id-error)
=> Fix job running despite existing JID

.github/workflows/test.yml
Currently, on the CI for cedana tests start even if the build fails. The base of PR is currently a failed build to test it out.
CED-388
=> Add build->test dependency in CI

.github/workflows/build.yml, .github/workflows/test.yml, api/process.go
Once a job that is run via `cedana exec ...` finishes, the state in the DB is not updated. It should say JOB_DONE.
CED-386
=> Update job state after it finishes

cmd/dump.go, cmd/flags.go, cmd/restore.go, cmd/runc.go
The base of the PR is intentionally `feat/ced-355`, to avoid conflicts.
For cedana restore runc ..., currently the argument needs absolute path, unlike its dump counterpart. This PR fixes that.
CED-391
=> Update runc restore root argument to take keyword

api/containerd.go, api/containerd/containerd.go, api/dump.go, api/services/cts.go, container/checkpoint.go, test/regression/helper.bash, test/regression/main.bats
- Modified containerd checkpoint to use a custom config spec json opt
- Modify dumprootfs function to use this containerd checkpoint from `container/checkpoint.go`
[CED-395](https://linear.app/cedana/issue/CED-395/fix-rootfs-restore-invalid-media-type)
=> resolve containerd rootfs restores

cmd/daemon.go, cmd/dump.go, cmd/exec.go, cmd/helper.go, cmd/ps.go, cmd/restore.go, cmd/root.go, cmd/runc.go, main.go
Currently, if the daemon or any other command in `cedana [cmd] …` results in an error, it does not exit with a non-zero code. This creates problems for the benchmark and tests that rely on error code to check for correct execution.
Also, fixes the issue where usage is printed even if it's not a usage error.
CED-415
=> Fix exit status on errors

api/services/cts.go
Currently, the deadline is causing issues with benchmarks when it runs some larger workloads. Deadline of 1 minute is too low.
CED-416
=> Relax daemon's runc context deadline

README.md
The `cedana client` command has been removed recently (https://github.com/cedana/cedana/pull/159). This pull request updates the checkpoint/restore examples in the README file to reflect these changes.
=> readme: update checkpoint/restore examples

scripts/k8s/setup-host.sh
- Added buildah install to k8s install script
n/a
=> fix: missing buildah dep for crio rootfs c/r

.github/workflows/benchmark-and-push.yml, .github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/test.yml
- Add an option to manually launch workflow with a Tmate SSH session. See https://github.com/marketplace/actions/debugging-with-tmate. Only actors who started the workflow can ssh using their private key.
- Upload missing logs to workflow artifacts where possible
CED-498
=> Improve debugging capabilities of CI workflows

api/crio/crio.go, go.mod, go.sum
- use auth.Login from containers repo to login to ecr registries
- auto detect ecr registry from image name
- decode and parse iam credentials from working node
[CED-515](https://linear.app/cedana/issue/CED-515/add-auth-login-steps-for-ecr)
=> Adds ability to login to ECR registries to push rootfs changes

api/server.go, api/streaming.go, build-start-daemon.sh
The daemon was hardcoded to print logs at `/var/log/cedana-daemon.log`. This should handled by redirection by whoever's spawning the daemon instead.
CED-579
=> Remove daemon log redirection embedded in daemon

.github/workflows/release.yml, Dockerfile
Everywhere in the CI, where we are building the cedana binary, the glibc version is 2.36. To support even just the base image ubuntu 20.04, we need to link with glibc version that is at most 2.30 (since it's forward compatible).
CED-586
=> Fix binary not built for lower glibc versions

api/services/cts.go
This would allow cedana commands to be executed while the daemon is not up yet, or has possibly crashed and is restarting. Could be useful in many cases, but currently need it for the design we're using for the Beam integration.
Please also look at #287, as this is based on that. Can be merged in any order, though.
CED-594
> Nope. This will turned off by default.
=> Add `wait_for_ready` option to CLI config

api/services/cts.go, cmd/config.go, cmd/daemon.go, cmd/root.go, types/config.go, utils/config.go
As of this PR: https://github.com/cedana/cedana/pull/256, the config file is now only for the daemon. As the CLI is now independent of daemon stuff, we still need a way to configure CLI options. 
This PR:
- Adds a new section called `cli` in `client_config.json`.
- Loads config during start itself now, instead of when daemon starts, as CLI options need to be available for other CLI commands.
- The `--config` & `--config-dir` options are now flags available to the `cedana ...` cmd instead of `cedana daemon start`.
CED-595
Does not touch existing daemon config at all, so no.
=> Add a CLI config section

api/process.go, api/server.go, cmd/daemon.go, test/regression/helper.bash, test/regression/main.bats
Currently, the healthcheck does a GPU health check regardless of whether the daemon was start with
`--gpu-enabled`. This was fixed.
Now, if GPU-support is not enabled in daemon, `cedana exec -g` will complain. Also, `cedana dump -g` will complain if trying to dump a job that is not 'managed' by the daemon, as the GPU-support is only possible for managed jobs.
CED-609
> New tests added.
> Move the GPU binary download logic to server. Now `StartServer` takes a `ServerOpts`, and `sevice` has persistent state flags `gpuEnabled` and `cudaVersion`.
=> CLI should ignore GPU if GPU not enabled in daemon

api/restore.go
This is needed for better backward compatibility, as it's older versions of `cedana-gpu` to always fail on `cedana restore`.
NA
=> hotfix: Don't error if GPU restore stats is nil

api/process.go
Currently, we are scanning the stdout/stderr-pipe and writing to a log file in a background routine, which is non-performant. Instead, it is possible to simply set the job's stdout/stderr before spawning the process.
CED-614
=> Directly set stdin/stderr of managed job instead of scanning

.github/workflows/pr.yml, .github/workflows/push.yml, .github/workflows/release.yml
Currently, tests are only run on a PR. An issue that only occures after merging to main will be missed. Before creating a release, we should be able to see that the tests pass on the main branch.
As show below, the 'green check mark' is missing on main branch:
Release workflow will now look like:
Creates a new 'Push' workflow that only runs on the main branch. Also runs the tests as part of the release workflow before publishing. Both simply reuse the existing PR workflow.
CED-615
> Manually tested by creating a tag. Thus, you will see a release workflow in the checks below.
=> Run all tests on push

api/criu.go, api/server.go, cmd/daemon.go, cmd/dump.go, cmd/restore.go, test/regression/main.bats
The health check must also do a `criu check` as the version check is not enough.
Also, now `cedana daemon check` will exit with a non-zero code if any of the checks fail.
CED-610
> Added healthcheck to regression tests.
=> Add `criu check` to healthcheck

.github/workflows/release.yml, scripts/ci/release-summary-slack
Would make sense to capture binary size changes from last, at least.
On release, a notification on slack using our CI bot would be nice so we are sure to keep an eye. Drafts a custom Slack message using the [Block Kit](https://api.slack.com/block-kit), so we can modify it as per need. For e.g., we could add a deps diff later on. 
Similar script is used for GPU benchmark Slack summaries as well, so it would make sense to create our own github action at some point, so it can be easily added to all repos. No action out there provides all the exact stuff we need.
CED-592
=> Capture more info during release & also post on slack

api/process.go, api/restore.go
There's a race condition where the daemon does not update the job state, if the program exits too early:
```bash
10:57AM INF process exited PID=29533 status=127
10:57AM INF managing process JID=ced PID=29533
10:57AM DBG gRPC request succeeded method
```
CED-620
> Simplifies the updation of state for both after `exec`ing and `restore`ing the job, so that the state is updated consistently. Also, ensures that the state is only updated in `process.go` and not touched by any of the internal functions.
=> Fix job state update on early exit

.github/pull_request_template.md, .github/workflows/pr.yml, scripts/ci/Makefile, scripts/ci/correctness-test.sh, test/benchmarks/process_json.py, test/benchmarks/requirements
Correctness is more of a test than a benchmark, so should be a separate CI job and should run on each PR alongside the regression tests.
CED-605
=> Move correctness tests as a separate CI job

cmd/exec.go, pkg/api/process.go, pkg/api/restore.go, pkg/api/server.go
Currently, if the GPU controller exits prematurely, the program will keep waiting indefinitely. The
program should be killed. Same behaviour is needed for after a GPU process is restored.
Also, logs after GPU controller exit were not being captured. They should be dumped in the daemon
logs. This was not happening because the stdout/stderr was being set after starting the process.
CED-631
> Nope.
=> Fix GPU controller error handling and log dump

cmd/dump.go, cmd/flags.go, pkg/api/runc.go, test/regression/helper.bash, test/regression/main.bats
Currently, a default value (true) is used for this CRIU option. We need an option to override from CLI.
BREAKING: The new default will be, thus, false. And this flag must be explicitly passed.
CED-639
> The new default will be, thus, false. And this flag must be explicitly passed.
=> Add `--leave-running` flag for runc

.github/workflows/manual.yml, .github/workflows/pr.yml, .github/workflows/release.yml
- Adds a PR job to run benchmark and post comparison w/ last patch on the PR as well as Slack to help catch performance regressions.
- Adds a release job to run benchmark and publish results to bigquery along with a post on Slack. All similar to the GPU benchmarks.
- Adds a manual workflow to trigger the benchmark manually on any branch, including an option to publish results to bigquery.
CED-646
=> Deploy `cedana-bench` to CI

pkg/api/server.go
**Why it was hard to find yesterday.** 
1. Only broken over firewall'ed networks, which is the case over k8s.
2. As well as protobufs were broken too.
This is why reverting was working, but fixing just protobufs alone was not working.
Both issues raise similar errors.
**How I found it?**
I tried connecting to it while debugging the grpc and saw that it was refusing the connection before validation, so it was fairly easy to resolve.
Also updated the protobufs on controller side. Everything is working now.
=> hotfix: hotfix grpc connection issue

cmd/scripts/k8s/setup-host.sh
- Add a stop cedana service portion before copying cedana binary
The purpose of this is to be able to upgrade cedana on a node that already has cedana just by stopping the service temporarily and copying over a new binary before starting a new systemctl service
=> fix: stop cedana before installing cedana

cmd/daemon.go, pkg/api/crio.go, pkg/api/server.go
very noisy stdout of pod after asr on k8s.
- makes asr less frequent now down to 60 seconds from 1 second.
- makes GetContainerInfo method trace log rather than debug log. As by default log level is debug, we don't get trace logs in stdout. use "CEDANA_LOG_LEVEL=trace" to adjust this.
=> fix: noisy stdout asr output

cmd/daemon.go, cmd/flags.go, pkg/api/server.go
Also check https://github.com/cedana/cedana-docs/pull/17
Currently, a flag, --cuda, needs to be passed to specify the GPU binary version to download.
Remove this flag and by default download the latest binary as it is now backward compatible.
NA
=> Update `cedana` for `cedana-gpu` driver API change

pkg/api/server.go
Currently, even if the startup poll RPC call fails, we continue to wait for timeout without printing the status of the RPC poll.
Should still be same, but with debug msg including any error msgs.
CED-692
=> Log on GPU controller startup poll error

cmd/scripts/k8s/setup-host.sh
Forgot to add back arm support after the previous revert due to setup bug elsewhere.
=> fix: add back arm64 support

pkg/api/kube/kube.go, pkg/api/runc.go, pkg/api/runc/runc.go
- Stop returning errors when runcquery doesn't find a container.
[CED-709](https://linear.app/cedana/issue/CED-709/move-failed-runc-queries-to-info-statements)
=> fix: stop returning errors that are non-errors in runcquery

docs/runc/gpu.md, pkg/api/process.go, pkg/api/runc.go
Currently, if the GPU controller fails to startup, the job still gets created in the DB.
CED-747
=> For `cedana manage`, handle GPU controller startup error properly

.github/workflows/manual.yml, .github/workflows/pr.yml, .github/workflows/release.yml
The legend only shows specs/tags that differ b/w results under comparison for brevity. 
Same as title. So that a plot image generated by the CI becomes standalone, and can be shared around without needing to share specs separately.
Plot flags can now be configured via the CI variable `BENCH_PLOT_FLAGS`.
CED-756
=> Show rest of the H/W specs within benchmark plots

pkg/api/server.go, setup-host.sh
Downloads were broken if you added the path, now it will ensure the download happens even if the path is specified. Also does them in parallel for perf & adds gpu flag if on nvidia supported node.
Ideally we will do all the setup in setup host but this improves the user experience for the end user. Also makes the logs for download "info" so it will be outputted to the user stdout by default.
Fixes CED-730
=> refactor: gpu binary downloads

.github/pull_request_template.md
Remove issue number from PR template, as it's already fetched from branch name and attached to the PR.
=> Remove issue number from PR template

pkg/api/dump.go, pkg/api/gpu.go, pkg/api/restore.go
If the shared memory file at /dev/shm/cedana-gpu.* is deleted after a dump. Or the restore happens on a new machine, the restore fails.
Do GPU restore before CRIU restore so GPU controller ensures that file is recreated. For now, this is fine as this file is of fixed size anyways.
For log files such as cedana-so-<jid>.log, uses a hack where gpuRestore simply creates an empty file before CRIU restore using the JID.
When the segment becomes dynamic in size, this won't work as CRIU will still complain about size mismatch. Also, if there are multiple segments. Ideally, GPU controller should return all such files info in RPC response to GPU restore, so we can just --inherit-fd them to CRIU.
=> fix: GPU shared memory segment migration issue

pkg/api/gpu.go
If the timeout expires, a GPU controller instance might keep running as an orphan. This fixes it, and also increases the timeout for slower systems.
=> hotfix: GPU controller leak + increase timeout

go.mod, go.sum, pkg/api/gpu.go, pkg/api/restore.go
**NOTE**: This will still not fix for runc GPU restores, as we don't have a CRIU notify hook for it. In the new unified design, it should be fixed.
If a checkpoint is taken during execution where the barrier flag is set, it breaks during the restore as it blocks gpu-controller from executing. 
This probably was introduced by moving the restore before the criu restore, which changed gpu-controller conking the flag over the head and unsetting it.
Add a new RPC function that unsets the barrier that gets called during a PreResume() hook, before the process starts.
=> fix: GPU restore barrier deadlock

Dockerfile, plugins/k8s/cmd/scripts/setup-host.sh
Install all plugins into the container image at the time of release by default, the images can be updated later.
Most importantly, this allows for k8s-helper code to work as it is.
=> chore: add k8s, etc plugins inside image

plugins/k8s/cmd/scripts/bump-restart.sh, plugins/k8s/cmd/scripts/setup-host.sh
cedana upgrade fails to copy cedana file, as it's running, keep this in case until we can provide a separate upgrade utility and binary
=> hotfix: upgrade cedana k8s broken

cmd/run.go, cmd/utils.go, pkg/config/config.go, pkg/config/types.go, pkg/profiling/timing.go
This is required by benchmark or other tools that want to read the data directly from stdout. Adds
the precision config item:
https://github.com/cedana/cedana/blob/2d924f8c81c8f7af8545587e3812d6793eeca95d/pkg/config/types.go#L57-L62
Default is "auto", which prints using the most suitable precision for the value.
=> feat: Allow setting custom precision for printing profiling data

internal/server/gpu/controller.go, internal/server/gpu/manager_simple.go
This race is caused when a restore is called immediately after a dump. Since for dump, the request
is returned as soon as dump is completed, while in the background the daemon cleans up the GPU
controller. If a restore is called immediately after the dump, a GPU controller might still appear
as attached to the job.
This fix fails restore request that happens too quickly, instead of segfaulting on the internal controller
map.
=> fix: GPU controller Attach called too quickly leading to race

cmd/run.go
Currently, when executing a process from the CLI, with `cedana exec/cedana run process`, passing in
the env vars to the daemon is not sufficient. The daemon is executing under a different env and so
the full path of the process must be provided to the daemon. For CLI, we simply resolve the full
path from where the command is called before passing it to the daemon.
=> fix: resolve full path in CLI for exec/run

internal/server/gpu/controller.go, pkg/config/types.go, pkg/logging/writer.go
https://github.com/cedana/cedana/blob/40cbf8c0b1f296febcd525b8367e4f130d7d9dfc/pkg/config/types.go#L95-L96
If option left empty, logs will appear in daemon stdout as before. If you set it to, for e.g.
`/var/log`, GPU controller will be written there.
=> feat: Add `log_dir` option to config for GPU logs

Makefile, cmd/plugin.go, pkg/plugins/feature.go, pkg/plugins/manager_local.go, pkg/plugins/manager_propagator.go, pkg/plugins/plugin.go, pkg/utils/time.go, scripts/ci/release-summary-slack
Updates the propagator plugin manager so that it only lists and downloads plugins that are
compatible with the current version of the binary. This is only needed for Go plugins, until we have
resolved the issues with cross-version compatibility. Other, external plugins like GPU, streamer are always
listed/downloaded latest. Even for external plugins, in the future, this would allow us to bind the binary to a compatible
version if there are breaking changes in the future.
Requires: https://github.com/cedana/cedana-propagator/pull/24
=> fix: List/download only compatible plugins from registry

internal/server/gpu/controller.go, pkg/config/config.go, pkg/config/types.go
1. If an incompatible old config file is found, a helpful error is thrown on launch.
2. Changes back config type to `json` as it's more easier to work with, especially if passing a
string config using the `--config` flag.
3. Fixes an issue where if CEDANA_URL/TOKEN are only set in the config file, and not the env, it wasn't being passed to the GPU controller.
=> fix: config error handling

plugins/runc/internal/device/dump_adapters.go, plugins/runc/internal/device/restore_adapters.go, plugins/runc/internal/filesystem/dump_adapters.go, plugins/runc/internal/filesystem/helpers.go
CRIU's ``--ext-mnt-map`` option is deprecated and will be removed in the future. This PR replaces
all instances of `--ext-mnt-map` with the new `--external` option.
=> fix: Replace all instances of CRIU ExtMountMap (deprecated)

internal/server/criu/dump_handlers.go
Noticed that the CRIU logging verbosity significantly slows down a dump, especially when dump a large container
with GPU support. This makes it so that CRIU will only log verbosely if Cedana's logging level is
set to debug/trace.
=> fix: CRIU logging verbosity

internal/server/process/restore_adapters.go, plugins/runc/internal/namespace/restore_adapters.go, test/regression/helpers/runc.bash, test/regression/plugins/runc.bats
If a container is using an external namespace, the namespace file needs to be opened by CRIU, so it
can `inherit-fd` it.
Also added tests for runc C/R, if a container has an external namespace or a combination of them.
=> fix: External namespace file not being passed in context

plugins/runc/internal/filesystem/dump_adapters.go, plugins/runc/internal/filesystem/helpers.go, plugins/runc/internal/filesystem/restore_adapters.go, test/regression/helpers/runc.bash, test/regression/plugins/runc.bats
Fixes external bind mounts that got broken due to: https://github.com/cedana/cedana/pull/486.
Also adds additional tests for this scenario.
=> fix: External bind mounts on runc restore

.github/workflows/pr.yml, internal/server/job/job.go, internal/server/job/manager_lazy.go, pkg/utils/process.go
When listing a job, through `cedana ps` for example, the jobs were being returned as is from the
DB/ram. Instead, we should always show the latest state of the job.
=> fix: Always show latest job state

go.mod, go.sum, internal/server/gpu/manager_simple.go, internal/server/job/job.go, internal/server/job/manager_lazy.go
Just like GPU restore, we can also dump GPU parallelly to CRIU dump.
Although, this requires the addition of a `Freeze` RPC call in the controller, so that the barrier
is acquired beforehand, and the actual dump can continue parallelly to the CRIU dump.
Accompanying PRs:
- cedana-api: https://github.com/cedana/cedana-api/pull/57
- cedana-gpu: https://github.com/cedana/cedana-gpu/pull/114
=> feat: Parallel GPU dump

pkg/utils/files.go, plugins/runc/internal/container/run_handlers.go, test/workloads/bundle/config.json
Since `cmd.Start` starts the process in the background, we need to wait for sometime before the
container is actually created, before proceeding. Similarly, if the cmd.Start fails, we need to
wait for some time until the process has actually exited before returning an error.
=> fix: runc run race condition on container creation

pkg/plugins/manager_propagator.go, scripts/host/k8s-install-plugins.sh
`cedana plugin list` would show this following warning if a plugin a supported plugin is not
available for the current binary version. E.g. here the k8s plugin is not available:
However, when you would do `cedana install k8s` it would still download the latest one and install
it. This PR fixes it.
=> fix: Don't install unsupported plugin

internal/server/streamer/fs.go
If the streamer failed to spawn, we were waiting for the entire timeout before returning an error.
This change makes it so that we return an error immediately if the streamer exits early.
=> fix: don't wait if streamer exits early on error

internal/server/gpu/controller.go, pkg/config/types.go
We do not have a tool that automates migration detection when a GPU is being underutilized, and this is the beginnings of one. We collect VRAM data in the form of allocations (cuMemAlloc) and frees (cuMemFree) in a file for visualizations. Later, this will be communicated to daemon at regular intervals.
Related: [GPU controller #127](https://github.com/cedana/cedana-gpu/pull/127)
=> GPU VRAM utilization

docs/guides/gpu/cr.md, internal/server/criu/checks_cuda.go, internal/server/healthcheck.go, pkg/plugins/manager_local.go, pkg/plugins/plugin.go, pkg/plugins/registry.go
Adds a `criu/cuda` plugin that enables CUDA checkpointing using just CRIU. [Docs have been updated](https://github.com/cedana/cedana/blob/feat/criu-cuda-plugin/docs/guides/gpu/cr.md) for GPU C/R to suggest this as an alternative option.
Also requires this propagator PR for it to be available in the registry: https://github.com/cedana/cedana-propagator/pull/30
A health check component has been added as well:
=> feat: Add criu/cuda plugin

cmd/dump.go, cmd/dump_vm.go, cmd/restore.go, internal/server/defaults/dump_vm_adapters.go, internal/server/dump_vm.go, test/regression/cr.bats
The dump `--dir` flag was not being recognized due to a bug (or feature?) in cobra/viper, when a
flag is bound to a config item more than once. For now, I've removed most of the flag bindings that
can potentially cause these failures, given that we have logic in the daemon already to read from
config when necessary.
=> fix: dump dir flag not being recognized

plugins/containerd/internal/filesystem/dump_adapters.go
We missed this, defer can run on context cancelled, but then context.Background is needed otherwise Resume won't happen.
This can happen often as containerd dump is very long.
I should also add a containerd test for this. 
Fixes CED-1093
=> hotfix: on cancel we should still resume pod

scripts/host/k8s-setup-host.sh, scripts/host/systemd-install.sh
Kubernetes needs Otel logging by default for us to have any visibility into daemons on clusters.
=> Feat: Default Otel logging in k8s

scripts/host/k8s-install-plugins.sh
In addition to using `command -v nvidia-smi &>/dev/null` to check whether the NVIDIA drivers exist, `[ -r /proc/driver/nvidia/version ]` checks for drivers as `nvidia-smi` is not installed on some GPU nodes.
=> CED-1426: Check for NVIDIA driver version to determine whether drivers are installed for cedana-helper

plugins/containerd/internal/gpu/run_adapters.go
Fixes GPU support for `cedana run containerd ...`
Below image is from running:
```bash
cedana run containerd -i docker.io/cedana/cedana-samples:cuda -ag -- 1 gpu_smr/vector_add
```
Same to run with native GPU support (assuming nvidia-container-toolkit is installed):
```bash
ctr run —gpus 0 docker.io/cedana/cedana-samples:cuda 1 gpu_smr/vector_add
```
=> CED-1611: Fix containerd GPU interception
